import type { Exercise, WorkoutDay, WorkoutPlan } from "@/db/schema";

export type { Exercise, WorkoutDay, WorkoutPlan };
export type { FeedbackEntry } from "@/db/schema";

export const INTENSITIES = ["low", "medium", "high"] as const;
export type Intensity = (typeof INTENSITIES)[number];

export const INTENSITY_LABELS: Record<Intensity, string> = {
  low: "Low",
  medium: "Moderate",
  high: "High",
};

export const GOAL_PRESETS = [
  "Build muscle",
  "Weight loss",
  "Strength",
  "Endurance",
  "Flexibility & mobility",
  "Athletic performance",
  "General fitness",
] as const;

export interface AthleteProfile {
  name: string;
  code: string;
  age: number;
  weightKg: number;
  goal: string;
  intensity: string;
}

/** Buckets a free-form goal string into a coarse key used by the fallback engine. */
export function goalKey(goal: string): string {
  const g = goal.toLowerCase();
  if (/(muscle|hypertrophy|bulk|gain|mass)/.test(g)) return "muscle";
  if (/(weight|fat|lean|cut|shred|slim)/.test(g)) return "fat";
  if (/(strength|power|strong)/.test(g)) return "strength";
  if (/(endurance|stamina|cardio|run|marathon)/.test(g)) return "endurance";
  if (/(flex|mobil|yoga|stretch)/.test(g)) return "mobility";
  if (/(athlet|sport|performance|speed|agility)/.test(g)) return "athletic";
  return "general";
}

export function isIntensity(value: unknown): value is Intensity {
  return (
    typeof value === "string" &&
    (INTENSITIES as readonly string[]).includes(value)
  );
}

/* ------------------------------------------------------------------ */
/* Defensive normalization of LLM output into our WorkoutPlan contract */
/* ------------------------------------------------------------------ */

function asString(value: unknown, fallback: string): string {
  if (typeof value === "string" && value.trim()) return value.trim();
  if (typeof value === "number" && Number.isFinite(value)) return String(value);
  return fallback;
}

function asInt(value: unknown, fallback: number, min: number, max: number): number {
  const n =
    typeof value === "number" ? value : parseInt(String(value ?? ""), 10);
  if (!Number.isFinite(n)) return fallback;
  return Math.min(max, Math.max(min, Math.round(n)));
}

function asRecord(value: unknown): Record<string, unknown> | null {
  if (value && typeof value === "object" && !Array.isArray(value)) {
    return value as Record<string, unknown>;
  }
  return null;
}

function normalizeExercise(raw: unknown, index: number): Exercise {
  const r = asRecord(raw) ?? {};
  return {
    name: asString(r.name ?? r.exercise, `Movement ${index + 1}`),
    sets: asInt(r.sets, 3, 1, 12),
    reps: asString(r.reps ?? r.repRange ?? r.duration, "10"),
    rest: asString(r.rest ?? r.restTime, "60s"),
    notes: r.notes ? asString(r.notes, "") || undefined : undefined,
  };
}

function normalizeDay(raw: unknown, index: number): WorkoutDay | null {
  const r = asRecord(raw);
  if (!r) return null;
  const exercisesRaw = Array.isArray(r.exercises) ? r.exercises : [];
  const exercises = exercisesRaw
    .map((e, i) => normalizeExercise(e, i))
    .filter((e) => e.name.trim().length > 0);
  return {
    day: asInt(r.day ?? r.dayNumber, index + 1, 1, 7),
    label: asString(r.label ?? r.title ?? r.name, `Day ${index + 1}`),
    focus: asString(r.focus ?? r.target, "Full body"),
    warmup: asString(r.warmup ?? r.warmUp, "5–10 min light cardio + dynamic stretches."),
    exercises: exercises.length
      ? exercises
      : [
          {
            name: "Brisk walk or easy cycle",
            sets: 1,
            reps: "20 min",
            rest: "—",
            notes: "Active recovery",
          },
        ],
    cooldown: asString(r.cooldown ?? r.coolDown, "5 min stretching + deep breathing."),
  };
}

/**
 * Converts arbitrary Gemini JSON into a guaranteed-valid 7-day plan.
 * Returns null when the payload has no usable day list.
 */
export function normalizePlan(input: unknown): WorkoutPlan | null {
  const r = asRecord(input);
  if (!r) return null;
  const daysRaw = Array.isArray(r.days) ? r.days : Array.isArray(r.week) ? r.week : null;
  if (!daysRaw || daysRaw.length === 0) return null;
  const days = daysRaw
    .map((d, i) => normalizeDay(d, i))
    .filter((d): d is WorkoutDay => d !== null)
    .slice(0, 7)
    .sort((a, b) => a.day - b.day);
  if (days.length === 0) return null;
  return {
    title: asString(r.title ?? r.planTitle, "7-Day Training Cycle"),
    overview: asString(
      r.overview ?? r.summary ?? r.description,
      "Personalized weekly split generated by FitBuddy.",
    ),
    coachNote:
      r.coachNote || r.coach_note ? asString(r.coachNote ?? r.coach_note, "") : null,
    days,
  };
}

/* ------------------------------------------------------------------ */
/* Lenient JSON parsing — tolerates code fences + truncated payloads   */
/* ------------------------------------------------------------------ */

/** Attempts to balance unclosed quotes/braces so truncated LLM JSON can parse. */
function repairTruncatedJson(text: string): string {
  let out = "";
  const stack: string[] = [];
  let inString = false;
  let escaped = false;
  for (const ch of text) {
    out += ch;
    if (escaped) {
      escaped = false;
      continue;
    }
    if (ch === "\\") {
      escaped = true;
      continue;
    }
    if (ch === '"') {
      inString = !inString;
      continue;
    }
    if (inString) continue;
    if (ch === "{" || ch === "[") stack.push(ch);
    else if (ch === "}") stack.pop();
    else if (ch === "]") stack.pop();
  }
  if (inString) out += '"';
  // Drop a possibly dangling trailing comma before closing structures.
  out = out.replace(/,\s*$/, "");
  while (stack.length) {
    const open = stack.pop();
    out += open === "{" ? "}" : "]";
  }
  return out;
}

export function parseLlmJson(text: string): unknown | null {
  let cleaned = text.trim();
  cleaned = cleaned.replace(/^```(?:json)?/i, "").replace(/```$/, "").trim();
  const start = cleaned.indexOf("{");
  if (start === -1) return null;
  cleaned = cleaned.slice(start);
  try {
    return JSON.parse(cleaned);
  } catch {
    try {
      return JSON.parse(repairTruncatedJson(cleaned));
    } catch {
      return null;
    }
  }
}

/** Stable 32-bit hash used to make the local fallback feel varied per athlete. */
export function hashSeed(input: string): number {
  let h = 2166136261;
  for (let i = 0; i < input.length; i++) {
    h ^= input.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}
